// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqt2HmegX3fbMTkccrHHezInl5A94BXdc',
    appId: '1:45041686936:web:fbf2efc2397ad382b0b3ed',
    messagingSenderId: '45041686936',
    projectId: 'login-3c8fb',
    authDomain: 'login-3c8fb.firebaseapp.com',
    databaseURL: 'https://login-3c8fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-3c8fb.appspot.com',
    measurementId: 'G-YM6126WPKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPmW4iJvMz6C77Rcz1WpUweEKPXI90fYg',
    appId: '1:45041686936:android:94dd760c93e994cfb0b3ed',
    messagingSenderId: '45041686936',
    projectId: 'login-3c8fb',
    databaseURL: 'https://login-3c8fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-3c8fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBidMWLN_SYei6JBT8ulaly62Hn5AvVGPI',
    appId: '1:45041686936:ios:4841643e95742e19b0b3ed',
    messagingSenderId: '45041686936',
    projectId: 'login-3c8fb',
    databaseURL: 'https://login-3c8fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-3c8fb.appspot.com',
    androidClientId: '45041686936-c1lmgv253aeg5otq3maconsommbjn23p.apps.googleusercontent.com',
    iosClientId: '45041686936-sqe3tgiteqh0dj4dvmgjrhtcskhg2rsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBidMWLN_SYei6JBT8ulaly62Hn5AvVGPI',
    appId: '1:45041686936:ios:a580e46cebc19039b0b3ed',
    messagingSenderId: '45041686936',
    projectId: 'login-3c8fb',
    databaseURL: 'https://login-3c8fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-3c8fb.appspot.com',
    androidClientId: '45041686936-c1lmgv253aeg5otq3maconsommbjn23p.apps.googleusercontent.com',
    iosClientId: '45041686936-hu27t91qo0d02dkti1258kpr6rkom64v.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleLogin.RunnerTests',
  );
}
